theme: jekyll-theme-cayman
title: Chai\'s Portfolio
description: Welcome to my portfolio! I am a passionate programmer and aspiring game developer. Since middleschool, I\'ve worked on dozens of personal projects spanning C++, C#, Java, Javascript, and more.
