theme: jekyll-theme-cayman
title: Chai's Portfolio
description: Welcome to my portfolio! I am a passionate programmer and aspiring game developer.

author: Chai
avatar: "https://i.imgur.com/clQTyxF.jpg"
