theme: jekyll-theme-cayman
title: Chai's Portfolio
description: Welcome to my portfolio! I am a passionate programmer and aspiring game developer.

author:
  name: Chai
  avatar: https://i.imgur.com/clQTyxF.jpg
  bio: I have a truly remarkable description about my profile but this margin is too small to contain it.
  github: VanillaChai
  youtube: https://www.youtube.com/channel/UCM8gUpHXdRf91Qcfr5tr8Xg
