theme: jekyll-theme-cayman
title: Chai's Portfolio
description: Welcome to my portfolio! I am a passionate programmer and aspiring game developer.

author:
  name             : "Your Sidebar Name"
  avatar           : "profile.png"
  bio              : "Your biography for the left-hand sidebar"
  location         : "Location"
